[project]
name = "ubigeos_peru"
version = "0.1.1"
readme = "README.md"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ubigeos_peru"]

[tool.setuptools.package-data]
"ubigeos_peru" = ["resources/*.json"]
