DEPARTAMENTOS = {
    "inei": {
        "01": "AMAZONAS",
        "02": "ANCASH",
        "03": "APURIMAC",
        "04": "AREQUIPA",
        "05": "AYACUCHO",
        "06": "CAJAMARCA",
        "07": "CALLAO",
        "08": "CUSCO",
        "09": "HUANCAVELICA",
        "10": "HUANUCO",
        "11": "ICA",
        "12": "JUNIN",
        "13": "LA LIBERTAD",
        "14": "LAMBAYEQUE",
        "15": "LIMA",
        "16": "LORETO",
        "17": "MADRE DE DIOS",
        "18": "MOQUEGUA",
        "19": "PASCO",
        "20": "PIURA",
        "21": "PUNO",
        "22": "SAN MARTIN",
        "23": "TACNA",
        "24": "TUMBES",
        "25": "UCAYALI",
    },
    "reniec": {
        "01": "AMAZONAS",
        "02": "ANCASH",
        "03": "APURIMAC",
        "04": "AREQUIPA",
        "05": "AYACUCHO",
        "06": "CAJAMARCA",
        "07": "CUSCO",
        "08": "HUANCAVELICA",
        "09": "HUANUCO",
        "10": "ICA",
        "11": "JUNIN",
        "12": "LA LIBERTAD",
        "13": "LAMBAYEQUE",
        "14": "LIMA",
        "15": "LORETO",
        "16": "MADRE DE DIOS",
        "17": "MOQUEGUA",
        "18": "PASCO",
        "19": "PIURA",
        "20": "PUNO",
        "21": "SAN MARTIN",
        "22": "TACNA",
        "23": "TUMBES",
        "24": "PROV. CONST. DEL CALLAO",
        "25": "UCAYALI",
    },
    "sunat": {
        "01": "AMAZONAS",
        "02": "ANCASH",
        "03": "APURIMAC",
        "04": "AREQUIPA",
        "05": "AYACUCHO",
        "06": "CAJAMARCA",
        "07": "PROV. CONST. DEL CALLAO",
        "08": "CUSCO",
        "09": "HUANCAVELICA",
        "10": "HUANUCO",
        "11": "ICA",
        "12": "JUNIN",
        "13": "LA LIBERTAD",
        "14": "LAMBAYEQUE",
        "15": "LIMA",
        "16": "LORETO",
        "17": "MADRE DE DIOS",
        "18": "MOQUEGUA",
        "19": "PASCO",
        "20": "PIURA",
        "21": "PUNO",
        "22": "SAN MARTIN",
        "23": "TACNA",
        "24": "TUMBES",
        "25": "UCAYALI",
    },
}
