MACRORREGIONES = {
    "ceplan": {
        "Amazonas": "norte",
        "Apurímac": "sur",
        "Arequipa": "sur",
        "Ayacucho": "sur",
        "Cajamarca": "norte",
        "Cusco": "sur",
        "Huancavelica": "sur",
        "Huánuco": "centro",
        "Ica": "sur",
        "Junín": "centro",
        "La Libertad": "norte",
        "Lambayeque": "norte",
        "Lima Metropolitana": "centro",
        "Lima Región": "centro",
        "Loreto": "nororiente",
        "Madre de Dios": "sur",
        "Moquegua": "sur",
        "Pasco": "centro",
        "Piura": "norte",
        "Puno": "sur",
        "San Martín": "norte",
        "Tacna": "sur",
        "Tumbes": "norte",
        "Ucayali": "nororiente",
        "Áncash": "centro",
    },
    "inei": {
        "AMAZONAS": "Oriente",
        "ANCASH": "Centro",
        "APURIMAC": "Sur",
        "AREQUIPA": "Sur",
        "AYACUCHO": "Centro",
        "CAJAMARCA": "Norte",
        "CALLAO": "Lima Metropolitana",
        "CUSCO": "Sur",
        "HUANCAVELICA": "Centro",
        "HUANUCO": "Centro",
        "ICA": "Centro",
        "JUNIN": "Centro",
        "LA LIBERTAD": "Norte",
        "LAMBAYEQUE": "Norte",
        "LIMA": "Lima Metropolitana",
        "LORETO": "Oriente",
        "MADRE DE DIOS": "Sur",
        "MOQUEGUA": "Sur",
        "PASCO": "Centro",
        "PIURA": "Norte",
        "PUNO": "Sur",
        "SAN MARTIN": "Oriente",
        "TACNA": "Sur",
        "TUMBES": "Norte",
        "UCAYALI": "Oriente",
    },
    "minsa": {
        "AMAZONAS": "Oriente",
        "ANCASH": "Norte",
        "APURIMAC": "Centro",
        "AREQUIPA": "Sur",
        "AYACUCHO": "Centro",
        "CAJAMARCA": "Norte",
        "CALLAO": "Lima y Callao",
        "CUSCO": "Sur",
        "HUANCAVELICA": "Centro",
        "HUANUCO": "Centro",
        "ICA": "Centro",
        "JUNIN": "Centro",
        "LA LIBERTAD": "Norte",
        "LAMBAYEQUE": "Norte",
        "LIMA": "Lima y Callao",
        "LORETO": "Oriente",
        "MADRE DE DIOS": "Sur",
        "MOQUEGUA": "Sur",
        "PASCO": "Centro",
        "PIURA": "Norte",
        "PUNO": "Sur",
        "SAN MARTIN": "Oriente",
        "TACNA": "Sur",
        "TUMBES": "Norte",
        "UCAYALI": "Oriente",
    },
}
