PROVINCIAS_EQUIVALENCIAS = {
    "ABANCAY": "Abancay",
    "ACOBAMBA": "Acobamba",
    "ACOMAYO": "Acomayo",
    "AIJA": "Aija",
    "ALTO AMAZONAS ": "Alto Amazonas ",
    "AMBO": "Ambo",
    "ANDAHUAYLAS": "Andahuaylas",
    "ANGARAES": "Angaraes",
    "ANTA": "Anta",
    "ANTABAMBA": "Antabamba",
    "ANTONIO RAYMONDI": "Antonio Raymondi",
    "AREQUIPA": "Arequipa",
    "ASCOPE ": "Ascope ",
    "ASUNCION": "Asunción",
    "ATALAYA ": "Atalaya ",
    "AYABACA ": "Ayabaca ",
    "AYMARAES": "Aymaraes",
    "AZANGARO ": "Azángaro ",
    "BAGUA": "Bagua",
    "BARRANCA ": "Barranca ",
    "BELLAVISTA ": "Bellavista ",
    "BOLIVAR ": "Bolívar ",
    "BOLOGNESI": "Bolognesi",
    "BONGARA": "Bongará",
    "CAJABAMBA": "Cajabamba",
    "CAJAMARCA": "Cajamarca",
    "CAJATAMBO ": "Cajatambo ",
    "CALCA": "Calca",
    "CAMANA": "Camaná",
    "CANAS": "Canas",
    "CANCHIS": "Canchis",
    "CANDARAVE ": "Candarave ",
    "CANETE ": "Cañete ",
    "CANGALLO": "Cangallo",
    "CANTA ": "Canta ",
    "CARABAYA ": "Carabaya ",
    "CARAVELI": "Caravelí",
    "CARHUAZ": "Carhuaz",
    "CARLOS FERMIN FITZCARRALD": "Carlos Fermín Fitzcarrald",
    "CASMA": "Casma",
    "CASTILLA": "Castilla",
    "CASTROVIRREYNA": "Castrovirreyna",
    "CAYLLOMA": "Caylloma",
    "CELENDIN": "Celendín",
    "CHACHAPOYAS": "Chachapoyas",
    "CHANCHAMAYO ": "Chanchamayo ",
    "CHEPEN ": "Chepén ",
    "CHICLAYO ": "Chiclayo ",
    "CHINCHA ": "Chincha ",
    "CHINCHEROS": "Chincheros",
    "CHOTA": "Chota",
    "CHUCUITO ": "Chucuito ",
    "CHUMBIVILCAS": "Chumbivilcas",
    "CHUPACA ": "Chupaca ",
    "CHURCAMPA": "Churcampa",
    "CONCEPCION ": "Concepción ",
    "CONDESUYOS": "Condesuyos",
    "CONDORCANQUI": "Condorcanqui",
    "CONTRALMIRANTE VILLAR ": "Contralmirante Villar ",
    "CONTUMAZA": "Contumazá",
    "CORONEL PORTILLO ": "Coronel Portillo ",
    "CORONGO": "Corongo",
    "COTABAMBAS": "Cotabambas",
    "CUSCO": "Cusco",
    "CUTERVO": "Cutervo",
    "DANIEL ALCIDES CARRION ": "Daniel Alcides Carrión ",
    "DATEM DEL MARANON ": "Datem del Marañón ",
    "DOS DE MAYO": "Dos de Mayo",
    "EL COLLAO ": "El Collao ",
    "EL DORADO ": "El Dorado ",
    "ESPINAR": "Espinar",
    "FERRENAFE ": "Ferreñafe ",
    "GENERAL SANCHEZ CERRO ": "General Sánchez Cerro ",
    "GRAN CHIMU ": "Gran Chimú ",
    "GRAU": "Grau",
    "HUACAYBAMBA": "Huacaybamba",
    "HUALGAYOC": "Hualgayoc",
    "HUALLAGA ": "Huallaga ",
    "HUAMALIES": "Huamalíes",
    "HUAMANGA": "Huamanga",
    "HUANCA SANCOS": "Huanca Sancos",
    "HUANCABAMBA ": "Huancabamba ",
    "HUANCANE ": "Huancané ",
    "HUANCAVELICA": "Huancavelica",
    "HUANCAYO ": "Huancayo ",
    "HUANTA": "Huanta",
    "HUANUCO": "Huánuco",
    "HUARAL ": "Huaral ",
    "HUARAZ": "Huaraz",
    "HUARI": "Huari",
    "HUARMEY": "Huarmey",
    "HUAROCHIRI ": "Huarochirí ",
    "HUAURA ": "Huaura ",
    "HUAYLAS": "Huaylas",
    "HUAYTARA": "Huaytará",
    "ICA ": "Ica ",
    "ILO ": "Ilo ",
    "ISLAY": "Islay",
    "JAEN": "Jaén",
    "JAUJA ": "Jauja ",
    "JORGE BASADRE ": "Jorge Basadre ",
    "JULCAN ": "Julcán ",
    "JUNIN ": "Junín ",
    "LA CONVENCION": "La Convención",
    "LA MAR": "La Mar",
    "LA UNION": "La Uniòn",
    "LAMAS ": "Lamas ",
    "LAMBAYEQUE ": "Lambayeque ",
    "LAMPA ": "Lampa ",
    "LAURICOCHA ": "Lauricocha ",
    "LEONCIO PRADO": "Leoncio Prado",
    "LIMA ": "Lima ",
    "LORETO ": "Loreto ",
    "LUCANAS": "Lucanas",
    "LUYA": "Luya",
    "MANU ": "Manu ",
    "MARANON": "Marañón",
    "MARISCAL CACERES ": "Mariscal Cáceres ",
    "MARISCAL LUZURIAGA": "Mariscal Luzuriaga",
    "MARISCAL NIETO ": "Mariscal Nieto ",
    "MARISCAL RAMON CASTILLA ": "Mariscal Ramón Castilla ",
    "MAYNAS ": "Maynas ",
    "MELGAR ": "Melgar ",
    "MOHO ": "Moho ",
    "MORROPON ": "Morropón ",
    "MOYOBAMBA ": "Moyobamba ",
    "NASCA ": "Nasca ",
    "OCROS": "Ocros",
    "OTUZCO ": "Otuzco ",
    "OXAPAMPA ": "Oxapampa ",
    "OYON ": "Oyón ",
    "PACASMAYO ": "Pacasmayo ",
    "PACHITEA": "Pachitea",
    "PADRE ABAD ": "Padre Abad ",
    "PAITA ": "Paita ",
    "PALLASCA": "Pallasca",
    "PALPA ": "Palpa ",
    "PARINACOCHAS": "Parinacochas",
    "PARURO": "Paruro",
    "PASCO ": "Pasco ",
    "PATAZ ": "Pataz ",
    "PAUCAR DEL SARA SARA": "Pàucar del Sara Sara",
    "PAUCARTAMBO": "Paucartambo",
    "PICOTA ": "Picota ",
    "PISCO ": "Pisco ",
    "PIURA ": "Piura ",
    "POMABAMBA": "Pomabamba",
    "PROV. CONST. DEL CALLAO": "Prov. Const. del Callao",
    "PUERTO INCA": "Puerto Inca",
    "PUNO ": "Puno ",
    "PURUS": "Purús",
    "PUTUMAYO": "Putumayo",
    "QUISPICANCHI": "Quispicanchi",
    "RECUAY": "Recuay",
    "REQUENA ": "Requena ",
    "RIOJA ": "Rioja ",
    "RODRIGUEZ DE MENDOZA": "Rodríguez de Mendoza",
    "SAN ANTONIO DE PUTINA ": "San Antonio de Putina ",
    "SAN IGNACIO": "San Ignacio",
    "SAN MARCOS": "San Marcos",
    "SAN MARTIN ": "San Martín ",
    "SAN MIGUEL": "San Miguel",
    "SAN PABLO": "San Pablo",
    "SAN ROMAN ": "San Román ",
    "SANCHEZ CARRION ": "Sánchez Carrión ",
    "SANDIA ": "Sandia ",
    "SANTA": "Santa",
    "SANTA CRUZ": "Santa Cruz",
    "SANTIAGO DE CHUCO ": "Santiago de Chuco ",
    "SATIPO ": "Satipo ",
    "SECHURA ": "Sechura ",
    "SIHUAS": "Sihuas",
    "SUCRE": "Sucre",
    "SULLANA ": "Sullana ",
    "TACNA ": "Tacna ",
    "TAHUAMANU ": "Tahuamanu ",
    "TALARA ": "Talara ",
    "TAMBOPATA ": "Tambopata ",
    "TARATA ": "Tarata ",
    "TARMA ": "Tarma ",
    "TAYACAJA": "Tayacaja",
    "TOCACHE ": "Tocache ",
    "TRUJILLO ": "Trujillo ",
    "TUMBES ": "Tumbes ",
    "UCAYALI ": "Ucayali ",
    "URUBAMBA": "Urubamba",
    "UTCUBAMBA": "Utcubamba",
    "VICTOR FAJARDO": "Víctor Fajardo",
    "VILCAS HUAMAN": "Vilcas Huamán",
    "VIRU ": "Virú ",
    "YAROWILCA ": "Yarowilca ",
    "YAULI ": "Yauli ",
    "YAUYOS ": "Yauyos ",
    "YUNGAY": "Yungay",
    "YUNGUYO ": "Yunguyo ",
    "ZARUMILLA ": "Zarumilla ",
}
